name: Build container image

on:
  push:
    tags:
    - 'v[0-9].[0-9]+.[0-9]+**'

env:
  IMAGE_REPO: llaoj/robot-j

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Variables
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          echo "image=${{ secrets.REGISTRY }}/${IMAGE_REPO}:${GIT_TAG}" >> $GITHUB_ENV

      - name: Build and push image to ACR
        run: |
          docker build -f build/Dockerfile -t ${{ env.image }} .
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
          docker push ${{ env.image }}
